// Implementation for: DevOps: - Task: Create a Dockerfile for the project.
   - Task: Set up the CI/CD pipeline in the .github/workflows/ci.yml file with the following steps:
     - Continuous integration using GitHub Actions.
     - Automated testing with pytest.
     - Building a Docker image and pushing it to Docker Hub.
     - Deployment to a staging environment on successful tests.
     - Integration of security scanning with bandit.
     - Configuration of pre-commit hooks for code quality.
// Generated by frontend_dev agent

