# Example configuration for using subprocess LLM provider (qwen CLI)
# Copy this to config.yaml and adjust as needed

version: 1.0

# LLM Configuration - Subprocess Provider (Real LLM via CLI)
llm:
  # Use subprocess provider for local qwen CLI
  provider: "subprocess"

  # Model is used as command name if subprocess_command not set
  model: "qwen"

  # No API key needed for local CLI tools
  api_key: null

  # Generation parameters
  temperature: 0.7
  max_tokens: 4000

  # Subprocess-specific settings
  subprocess_command: "qwen"  # Command to execute (ensure it's in PATH)
  subprocess_timeout: 300     # Timeout in seconds (5 minutes)
  subprocess_extra_args:
    # Pass tools that qwen agent should have access to
    tools: "file_read,file_write,shell"
    # Enable verbose output for debugging
    # verbose: true

# Scratchpad settings
default_max_scratchpad_chars: 8192

# Tool permissions (passed to all agents)
default_allowed_tools:
  - file_read
  - file_write
  - shell

# Logging
log_level: INFO

# Network settings
clarification_server_port_range:
  min: 8000
  max: 9000

# Agent execution
agent_timeout_seconds: 300

# Status monitoring
enable_status_display: true
status_refresh_seconds: 2
status_display_width: 60
status_display_tail_lines: 3
