# Global configuration for MSP Orchestrator
version: 1.0

# LLM Configuration
llm:
  # Provider: "openai", "anthropic", "ollama", "subprocess", or "mock"
  # - "subprocess": For local CLI tools like qwen, claude-code (RECOMMENDED - True LLM intelligence)
  # - "ollama": For Ollama local models via HTTP API
  # - "openai": For OpenAI GPT models
  # - "anthropic": For Anthropic Claude models
  # - "mock": For testing without real LLM (uses hardcoded responses - NOT universal)
  provider: "mock"  # Using mock for testing

  # Model name (provider-specific)
  # OpenAI: "gpt-4", "gpt-3.5-turbo"
  # Anthropic: "claude-3-5-sonnet-20241022", "claude-3-opus-20240229"
  # Ollama: "qwen2.5-coder:7b", "codellama:13b", "mistral:latest"
  # Subprocess: Command name (e.g., "qwen", "claude")
  model: null  # Will use provider defaults

  # API Key (use ${ENV_VAR} syntax to load from environment)
  # For OpenAI: Set OPENAI_API_KEY environment variable
  # For Anthropic: Set ANTHROPIC_API_KEY environment variable
  # Not needed for subprocess, ollama, or mock
  api_key: null

  # Generation parameters
  temperature: 0.7
  max_tokens: 4000

  # Ollama-specific settings
  ollama_host: "http://localhost:11434"

  # Subprocess-specific settings (for CLI-based LLMs)
  subprocess_command: "C:\\Users\\Дарья\\AppData\\Roaming\\npm\\qwen.cmd"  # Full path to qwen
  subprocess_timeout: 300     # Timeout in seconds
  subprocess_extra_args: {}   # Extra CLI arguments as key-value pairs
    # Example:
    # tools: "file_read,file_write,shell"
    # verbose: true

# Scratchpad settings
default_max_scratchpad_chars: 8192

# Tool permissions
default_allowed_tools:
  - file_read
  - file_write
  - shell

# Logging
log_level: INFO
log_format: "[%(asctime)s] %(levelname)s - %(name)s - %(message)s"

# Network settings
clarification_server_port_range:
  min: 8000
  max: 9000

default_agent_port: 8000

# Agent execution
agent_timeout_seconds: 300

# Validation
default_validation_level: standard

# Status monitoring
enable_status_display: true
status_refresh_seconds: 2
status_display_width: 60
status_display_tail_lines: 3

# Default application values (for code generation)
default_app_title: "Task Management API"
default_app_version: "1.0.0"

# System limits
syntax_check_timeout_seconds: 10
max_port_search_attempts: 100
thread_join_timeout_seconds: 1

# Scratchpad behavior
scratchpad_truncation_strategy: "keep_end"